### ISSUE TITLE
Compilation fails for Bears_INRIA-spoon_189186902-189233591

### ISSUE THREAD

**Issue by DehengYang** [bears-bugs/bears-benchmark#331]
Hello, 

Sorry for interrupting you here. I would like to report on a compilation issue to you for your help. The detail is as follows:

I leverage RepairThemAll to checkout the Bears_INRIA-spoon_189186902-189233591 buggy version. Then, I run `mvn compile` in this folder but received the following errors:

> [INFO] 15 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.404 s
[INFO] Finished at: 2021-12-18T16:01:20+08:00
[INFO] Final Memory: 28M/547M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project spoon-core: Compilation failure: Compilation failure:
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/compiler/builder/SourceOptions.java:[19,29] cannot find symbol
[ERROR] symbol:   class IOUtils
[ERROR] location: package org.apache.commons.io
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java:[20,29] cannot find symbol
[ERROR] symbol:   class IOUtils
[ERROR] location: package org.apache.commons.io
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java:[19,36] cannot find symbol
[ERROR] symbol:   class NullOutputStream
[ERROR] location: package org.apache.commons.io.output
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/support/compiler/jdt/FileCompilerConfig.java:[27,29] cannot find symbol
[ERROR] symbol:   class IOUtils
[ERROR] location: package org.apache.commons.io
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/Launcher.java:[27,40] cannot find symbol
[ERROR] symbol:   class IOFileFilter
[ERROR] location: package org.apache.commons.io.filefilter
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/Launcher.java:[673,29] cannot find symbol
[ERROR] symbol:   class IOFileFilter
[ERROR] location: class spoon.Launcher
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/Launcher.java:[685,29] cannot find symbol
[ERROR] symbol:   class IOFileFilter
[ERROR] location: class spoon.Launcher
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/Launcher.java:[673,70] cannot find symbol
[ERROR] symbol:   class IOFileFilter
[ERROR] location: class spoon.Launcher
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/Launcher.java:[685,63] cannot find symbol
[ERROR] symbol:   class IOFileFilter
[ERROR] location: class spoon.Launcher
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/compiler/builder/SourceOptions.java:[61,41] cannot find symbol
[ERROR] symbol:   variable IOUtils
[ERROR] location: class spoon.compiler.builder.SourceOptions<T>
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java:[406,96] cannot find symbol
[ERROR] symbol:   method listFiles(java.io.File,java.lang.String[],boolean)
[ERROR] location: class org.apache.commons.io.FileUtils
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java:[502,33] cannot find symbol
[ERROR] symbol:   variable IOUtils
[ERROR] location: class spoon.support.compiler.jdt.JDTBasedSpoonCompiler
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java:[54,39] cannot find symbol
[ERROR] symbol:   class NullOutputStream
[ERROR] location: class spoon.support.compiler.jdt.JDTBatchCompiler
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java:[54,63] cannot find symbol
[ERROR] symbol:   class NullOutputStream
[ERROR] location: class spoon.support.compiler.jdt.JDTBatchCompiler
[ERROR] /mnt/data/benchmarks/bugs/Bears/Bears_INRIA-spoon_189186902-189233591/src/main/java/spoon/support/compiler/jdt/FileCompilerConfig.java:[71,64] cannot find symbol
[ERROR] symbol:   variable IOUtils
[ERROR] location: class spoon.support.compiler.jdt.FileCompilerConfig
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

After some explorations, I found that this error is caused by the maven project dependency conflicts. Concretely, I ran `mvn dependency:tree -Dverbose`, and it outputed:
```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Spoon Core 5.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ spoon-core ---
[INFO] fr.inria.gforge.spoon:spoon-core:jar:5.5.0-SNAPSHOT
[INFO] +- org.eclipse.tycho:org.eclipse.jdt.core:jar:3.12.0.v20160516-2131:compile
[INFO] +- junit:junit:jar:4.11:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- com.github.stefanbirkner:system-rules:jar:1.9.0:test
[INFO] |  +- (junit:junit:jar:4.11:test - omitted for duplicate)
[INFO] |  \- (commons-io:commons-io:jar:20030203.000550:test - omitted for duplicate)
[INFO] +- org.mockito:mockito-all:jar:2.0.2-beta:test
[INFO] +- com.martiansoftware:jsap:jar:2.1:compile
[INFO] +- ant:ant:jar:1.6.5:provided
[INFO] +- log4j:log4j:jar:1.2.17:compile
[INFO] \- commons-io:commons-io:jar:20030203.000550:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.265 s
[INFO] Finished at: 2021-12-18T16:03:20+08:00
[INFO] Final Memory: 19M/417M
```

However, as stated in the pom.xml of this project, it relies on `commons-io:1.4` rather than `commons-io:20030203.000550`. Seemingly the `com.github.stefanbirkner:system-rules:jar:1.9.0:test` dependency conflicts the needed `commons-io:1.4`  jar.

As a workaround, I changed the pom.xml as follows (i.e., by adding exclusion block into the stefanbirkner dependency block):
```
    <dependency>
      <groupId>com.github.stefanbirkner</groupId>
      <artifactId>system-rules</artifactId>
      <version>1.9.0</version>
	<exclusions>
            <exclusion>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
            </exclusion>
        </exclusions>
      <scope>test</scope>
    </dependency>
```

The compilation errors are then resolved.

Here I would like to report on this issue to you, and I would like to ask that have you ever encountered such issue? and is there a better and automated solution for it? It would be much appreciated if any help could be provided. Thank you!

**Comment by monperrus** [comment]
yes, it's known that `mvn test` is not enough, the expected command should be

    mvn test -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -DskipITs=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true 

See https://github.com/bears-bugs/bears-benchmark/blob/master/scripts/run_tests_bug.py#L41
